
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-connect:
    image: debezium/connect:2.5
    container_name: kafka-connect
    restart: always
    depends_on:
      - kafka
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      GROUP_ID: "1"
      CONFIG_STORAGE_TOPIC: "connect-configs"
      OFFSET_STORAGE_TOPIC: "connect-offsets"
      STATUS_STORAGE_TOPIC: "connect-status"
    volumes:
      - ./debezium-plugins:/kafka/connect/debezium-plugins

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customer_orders
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Optional: Oracle for local testing
  oracle:
    image: gvenzl/oracle-xe:latest
    container_name: oracle
    restart: always
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: purple1
      ORACLE_USER: system
      ORACLE_DB: XEPDB1
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  pgdata:
  oracle-data:
