version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

#  connect:
#    image: debezium/connect:latest
#    container_name: kafka-connect
#    ports:
#      - "8083:8083"
#    depends_on:
#      - kafka
#    environment:
#      BOOTSTRAP_SERVERS: kafka:9092
#      GROUP_ID: "1"
#      CONFIG_STORAGE_TOPIC: debezium_connect_configs
#      OFFSET_STORAGE_TOPIC: debezium_connect_offsets
#      STATUS_STORAGE_TOPIC: debezium_connect_status
#      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
#      CONNECT_PLUGIN_PATH: /kafka/connect
#    volumes:
#      - ./kafka-data:/kafka/connect